version: "3.3"

services:
  react-app:
    build: .
    container_name: react-rick
    ports:
      - "3000:3000"
    volumes:
      - ./app:/usr/src/app
      - /usr/src/app/node_modules
    stdin_open: true
    tty: true
    command: sh -c "cd app && npm install && npm start"
